### PR TITLE
Fix and new commit from adk-server.

### PR DESCRIPTION
**Pull request by Zeeerooo**
Fixes: Port was opened in another container, not the right one.

### CODE REVIEW

**Comment by fmontoto** [comment]
Next time use a more descriptive name for commits and pull requests, if you're fixing something say what is it.

**Comment by Zeeerooo** [comment]
@fmontoto added fixes to the comments of the PR.

**Comment by fmontoto** [comment]
lgtm

**Comment by camilog** [comment]
LGTM

**Pull request merged**
